# Generated by Django 4.2.13 on 2024-07-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_lander_creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='expires_in',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
