# Generated by Django 4.2.13 on 2024-07-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_lander_creator', '0002_alter_oauthtoken_expires_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
